//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionAI.Core.Models {
    
    public class Evomodels {
        public sealed class Subway_Surfer {
            public const string model_type = "gaming";
            public const int beta_id = 2115;
            public const int prod_id = 2129;
            public const string name = "subway-surfer";
            public sealed class Movements {
                public sealed class Duck {
                    public const string name = "duck";
                    public const int id = 90;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum duck_down = MotionAI.Core.Models.Constants.ElmoEnum.duck_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum duck_up = MotionAI.Core.Models.Constants.ElmoEnum.duck_up;
                    }
                }
                public sealed class Hop_Single {
                    public const string name = "hop_single";
                    public const int id = 115;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_down;
                    }
                }
                public sealed class Turn_90_Right {
                    public const string name = "turn_90_right";
                    public const int id = 101;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum turn_90_right = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_right;
                    }
                }
                public sealed class Turn_90_Left {
                    public const string name = "turn_90_left";
                    public const int id = 102;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum turn_90_left = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_left;
                    }
                }
                public sealed class Turn_90 {
                    public const string name = "turn_90";
                    public const int id = 103;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum turn_90 = MotionAI.Core.Models.Constants.ElmoEnum.turn_90;
                    }
                }
                public sealed class Side_Step {
                    public const string name = "side_step";
                    public const int id = 106;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_up;
                    }
                }
                public sealed class Side_Step_Left {
                    public const string name = "side_step_left";
                    public const int id = 110;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_left_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_left_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_up;
                    }
                }
                public sealed class Side_Step_Right {
                    public const string name = "side_step_right";
                    public const int id = 111;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_right_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum side_step_right_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_down;
                    }
                }
            }
        }
        public sealed class Bodyweight {
            public const string model_type = "fitness";
            public const int beta_id = 1915;
            public const int prod_id = 0;
            public const string name = "bodyweight";
            public sealed class Movements {
                public sealed class Bench_Dip {
                    public const string name = "bench_dip";
                    public const int id = 6;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum bench_dip_up = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum bench_dip_down = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_down;
                    }
                }
                public sealed class Jumping_Jack {
                    public const string name = "jumping_jack";
                    public const int id = 5;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_up;
                    }
                }
                public sealed class Mountain_Climbers {
                    public const string name = "mountain_climbers";
                    public const int id = 10;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_down;
                    }
                }
                public sealed class Lunge {
                    public const string name = "lunge";
                    public const int id = 12;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum lunge_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum lunge_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_down;
                    }
                }
                public sealed class Burpee {
                    public const string name = "burpee";
                    public const int id = 24;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum burpee_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_back_pushup_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_back_pushup_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_forward_pushup_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_forward_pushup_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum burpee_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_up;
                    }
                }
                public sealed class Squat_Jump {
                    public const string name = "squat_jump";
                    public const int id = 19;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum squat_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum squat_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_down;
                    }
                }
                public sealed class High_Knees {
                    public const string name = "high_knees";
                    public const int id = 26;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum high_knees_down = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum high_knees_up = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_up;
                    }
                }
                public sealed class Hip_Raise {
                    public const string name = "hip_raise";
                    public const int id = 28;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum hip_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum hip_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_down;
                    }
                }
                public sealed class Calf_Raise {
                    public const string name = "calf_raise";
                    public const int id = 32;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum calf_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum calf_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_down;
                    }
                }
                public sealed class Plank {
                    public const string name = "plank";
                    public const int id = 33;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum plank = MotionAI.Core.Models.Constants.ElmoEnum.plank;
                    }
                }
                public sealed class Climbers {
                    public const string name = "climbers";
                    public const int id = 34;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum climber_up = MotionAI.Core.Models.Constants.ElmoEnum.climber_up;
                        public const MotionAI.Core.Models.Constants.ElmoEnum climber_down = MotionAI.Core.Models.Constants.ElmoEnum.climber_down;
                    }
                }
                public sealed class Plank_Jack {
                    public const string name = "plank_jack";
                    public const int id = 39;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum plank_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum plank_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_up;
                    }
                }
                public sealed class Lunge_Reverse {
                    public const string name = "lunge_reverse";
                    public const int id = 41;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_up;
                    }
                }
                public sealed class Good_Morning {
                    public const string name = "good_morning";
                    public const int id = 40;
                    public sealed class Elmos {
                        public const MotionAI.Core.Models.Constants.ElmoEnum good_morning_down = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_down;
                        public const MotionAI.Core.Models.Constants.ElmoEnum good_morning_up = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_up;
                    }
                }
            }
        }
    }
}
