//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace MotionAI.Core.Models.Evomodels {
    
    public class Subway_Surfer : AbstractModelComponent {
        public string bruh;
        public static string model_type {
            get {
                return "gaming";
            }
        }
        public static int beta_id {
            get {
                return 2115;
            }
        }
        public static int prod_id {
            get {
                return 2129;
            }
        }
        public static string name {
            get {
                return "subway-surfer";
            }
        }
        public enum Elmos {
            duck_down = MotionAI.Core.Models.Constants.ElmoEnum.duck_down,
            duck_up = MotionAI.Core.Models.Constants.ElmoEnum.duck_up,
            hop_single_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_up,
            hop_single_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_down,
            turn_90_right = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_right,
            turn_90_left = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_left,
            turn_90 = MotionAI.Core.Models.Constants.ElmoEnum.turn_90,
            side_step_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_down,
            side_step_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_up,
            side_step_left_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_down,
            side_step_left_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_up,
            side_step_right_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_up,
            side_step_right_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_down,
        }
        public class Movements {
            public class Duck {
                public static string name {
                    get {
                        return "duck";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.duck;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum duck_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.duck_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum duck_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.duck_up;
                        }
                    }
                }
            }
            public class Hop_Single {
                public static string name {
                    get {
                        return "hop_single";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.hop_single;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum hop_single_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.hop_single_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum hop_single_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.hop_single_down;
                        }
                    }
                }
            }
            public class Turn_90_Right {
                public static string name {
                    get {
                        return "turn_90_right";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.turn_90_right;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum turn_90_right {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.turn_90_right;
                        }
                    }
                }
            }
            public class Turn_90_Left {
                public static string name {
                    get {
                        return "turn_90_left";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.turn_90_left;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum turn_90_left {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.turn_90_left;
                        }
                    }
                }
            }
            public class Turn_90 {
                public static string name {
                    get {
                        return "turn_90";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.turn_90;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum turn_90 {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.turn_90;
                        }
                    }
                }
            }
            public class Side_Step {
                public static string name {
                    get {
                        return "side_step";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.side_step;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_up;
                        }
                    }
                }
            }
            public class Side_Step_Left {
                public static string name {
                    get {
                        return "side_step_left";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.side_step_left;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_left_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_left_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_up;
                        }
                    }
                }
            }
            public class Side_Step_Right {
                public static string name {
                    get {
                        return "side_step_right";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.side_step_right;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_right_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum side_step_right_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_down;
                        }
                    }
                }
            }
        }
    }
    
    public class Bodyweight  : AbstractModelComponent {
        public string nigga = "bruuuh";
        public static string model_type {
            get {
                return "fitness";
            }
        }
        public static int beta_id {
            get {
                return 1915;
            }
        }
        public static int prod_id {
            get {
                return 0;
            }
        }
        public static string name {
            get {
                return "bodyweight";
            }
        }
        public enum Elmos {
            bench_dip_up = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_up,
            bench_dip_down = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_down,
            jumping_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_down,
            jumping_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_up,
            mountain_climber_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_up,
            mountain_climber_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_down,
            lunge_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_up,
            lunge_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_down,
            burpee_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_down,
            burpee_snap_back_pushup_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_back_pushup_down,
            burpee_snap_forward_pushup_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_forward_pushup_up,
            burpee_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_up,
            squat_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_up,
            squat_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_down,
            high_knees_down = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_down,
            high_knees_up = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_up,
            hip_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_up,
            hip_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_down,
            calf_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_up,
            calf_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_down,
            plank = MotionAI.Core.Models.Constants.ElmoEnum.plank,
            climber_up = MotionAI.Core.Models.Constants.ElmoEnum.climber_up,
            climber_down = MotionAI.Core.Models.Constants.ElmoEnum.climber_down,
            plank_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_down,
            plank_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_up,
            lunge_reverse_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_down,
            lunge_reverse_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_up,
            good_morning_down = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_down,
            good_morning_up = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_up,
        }
        public class Movements {
            public class Bench_Dip {
                public static string name {
                    get {
                        return "bench_dip";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.bench_dip;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum bench_dip_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum bench_dip_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_down;
                        }
                    }
                }
            }
            public class Jumping_Jack {
                public static string name {
                    get {
                        return "jumping_jack";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.jumping_jack;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_up;
                        }
                    }
                }
            }
            public class Mountain_Climbers {
                public static string name {
                    get {
                        return "mountain_climbers";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.mountain_climbers;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_down;
                        }
                    }
                }
            }
            public class Lunge {
                public static string name {
                    get {
                        return "lunge";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.lunge;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum lunge_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.lunge_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum lunge_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.lunge_down;
                        }
                    }
                }
            }
            public class Burpee {
                public static string name {
                    get {
                        return "burpee";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.burpee;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum burpee_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.burpee_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_back_pushup_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_back_pushup_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_forward_pushup_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_forward_pushup_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum burpee_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.burpee_up;
                        }
                    }
                }
            }
            public class Squat_Jump {
                public static string name {
                    get {
                        return "squat_jump";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.squat_jump;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum squat_jump_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum squat_jump_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_down;
                        }
                    }
                }
            }
            public class High_Knees {
                public static string name {
                    get {
                        return "high_knees";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.high_knees;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum high_knees_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.high_knees_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum high_knees_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.high_knees_up;
                        }
                    }
                }
            }
            public class Hip_Raise {
                public static string name {
                    get {
                        return "hip_raise";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.hip_raise;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum hip_raise_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum hip_raise_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_down;
                        }
                    }
                }
            }
            public class Calf_Raise {
                public static string name {
                    get {
                        return "calf_raise";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.calf_raise;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum calf_raise_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum calf_raise_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_down;
                        }
                    }
                }
            }
            public class Plank {
                public static string name {
                    get {
                        return "plank";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.plank;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum plank {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.plank;
                        }
                    }
                }
            }
            public class Climbers {
                public static string name {
                    get {
                        return "climbers";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.climbers;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum climber_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.climber_up;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum climber_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.climber_down;
                        }
                    }
                }
            }
            public class Plank_Jack {
                public static string name {
                    get {
                        return "plank_jack";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.plank_jack;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum plank_jack_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum plank_jack_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_up;
                        }
                    }
                }
            }
            public class Lunge_Reverse {
                public static string name {
                    get {
                        return "lunge_reverse";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.lunge_reverse;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_up;
                        }
                    }
                }
            }
            public class Good_Morning {
                public static string name {
                    get {
                        return "good_morning";
                    }
                }
                public static MotionAI.Core.Models.Constants.MovementEnum id {
                    get {
                        return MotionAI.Core.Models.Constants.MovementEnum.good_morning;
                    }
                }
                public class Elmos {
                    public static MotionAI.Core.Models.Constants.ElmoEnum good_morning_down {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.good_morning_down;
                        }
                    }
                    public static MotionAI.Core.Models.Constants.ElmoEnum good_morning_up {
                        get {
                            return MotionAI.Core.Models.Constants.ElmoEnum.good_morning_up;
                        }
                    }
                }
            }
        }
    }
}
