//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotionAI.Core.Models {
    
    public class Movements {
        public static class Arm_Spin {
            public const string name = "arm_spin";
            public const int id = 86;
            public const MotionAI.Core.Models.Constants.ElmoEnum arm_spin_up = MotionAI.Core.Models.Constants.ElmoEnum.arm_spin_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum arm_spin_down = MotionAI.Core.Models.Constants.ElmoEnum.arm_spin_down;
        }
        public sealed class Bench_Dip {
            public const string name = "bench_dip";
            public const int id = 6;
            public const MotionAI.Core.Models.Constants.ElmoEnum bench_dip_up = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum bench_dip_down = MotionAI.Core.Models.Constants.ElmoEnum.bench_dip_down;
        }
        public sealed class Bench_Press {
            public const string name = "bench_press";
            public const int id = 68;
            public const MotionAI.Core.Models.Constants.ElmoEnum bench_press_up = MotionAI.Core.Models.Constants.ElmoEnum.bench_press_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum bench_press_down = MotionAI.Core.Models.Constants.ElmoEnum.bench_press_down;
        }
        public sealed class Benchpress_Pullup {
            public const string name = "benchpress_pullup";
            public const int id = 72;
            public const MotionAI.Core.Models.Constants.ElmoEnum pp_pu_up = MotionAI.Core.Models.Constants.ElmoEnum.pp_pu_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum bb_pu_down = MotionAI.Core.Models.Constants.ElmoEnum.bb_pu_down;
        }
        public sealed class Burpee {
            public const string name = "burpee";
            public const int id = 24;
            public const MotionAI.Core.Models.Constants.ElmoEnum burpee_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_back_pushup_down = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_back_pushup_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum burpee_snap_forward_pushup_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_snap_forward_pushup_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum burpee_up = MotionAI.Core.Models.Constants.ElmoEnum.burpee_up;
        }
        public sealed class Butterfly {
            public const string name = "butterfly";
            public const int id = 73;
            public const MotionAI.Core.Models.Constants.ElmoEnum butterfly_open = MotionAI.Core.Models.Constants.ElmoEnum.butterfly_open;
            public const MotionAI.Core.Models.Constants.ElmoEnum butterfly_close = MotionAI.Core.Models.Constants.ElmoEnum.butterfly_close;
        }
        public sealed class Butterfly_Reverse {
            public const string name = "butterfly_reverse";
            public const int id = 75;
            public const MotionAI.Core.Models.Constants.ElmoEnum butterfly_open = MotionAI.Core.Models.Constants.ElmoEnum.butterfly_open;
            public const MotionAI.Core.Models.Constants.ElmoEnum butterfly_close = MotionAI.Core.Models.Constants.ElmoEnum.butterfly_close;
        }
        public sealed class Calf_Raise {
            public const string name = "calf_raise";
            public const int id = 32;
            public const MotionAI.Core.Models.Constants.ElmoEnum calf_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum calf_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.calf_raise_down;
        }
        public sealed class Pullup {
            public const string name = "pullup";
            public const int id = 4;
            public const MotionAI.Core.Models.Constants.ElmoEnum pullup_down = MotionAI.Core.Models.Constants.ElmoEnum.pullup_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum pullup_up = MotionAI.Core.Models.Constants.ElmoEnum.pullup_up;
        }
        public sealed class Climbers {
            public const string name = "climbers";
            public const int id = 34;
            public const MotionAI.Core.Models.Constants.ElmoEnum climber_up = MotionAI.Core.Models.Constants.ElmoEnum.climber_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum climber_down = MotionAI.Core.Models.Constants.ElmoEnum.climber_down;
        }
        public sealed class Crunch {
            public const string name = "crunch";
            public const int id = 15;
            public const MotionAI.Core.Models.Constants.ElmoEnum crunch_up = MotionAI.Core.Models.Constants.ElmoEnum.crunch_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum cruch_down = MotionAI.Core.Models.Constants.ElmoEnum.cruch_down;
        }
        public sealed class Curl {
            public const string name = "curl";
            public const int id = 42;
            public const MotionAI.Core.Models.Constants.ElmoEnum curl_down = MotionAI.Core.Models.Constants.ElmoEnum.curl_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum curl_up = MotionAI.Core.Models.Constants.ElmoEnum.curl_up;
        }
        public sealed class Db_Bench_Press {
            public const string name = "db_bench_press";
            public const int id = 120;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_bench_press_down = MotionAI.Core.Models.Constants.ElmoEnum.db_bench_press_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_bench_press_up = MotionAI.Core.Models.Constants.ElmoEnum.db_bench_press_up;
        }
        public sealed class Db_Curl {
            public const string name = "db_curl";
            public const int id = 118;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_curl_up = MotionAI.Core.Models.Constants.ElmoEnum.db_curl_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_curl_down = MotionAI.Core.Models.Constants.ElmoEnum.db_curl_down;
        }
        public sealed class Db_Deadlift {
            public const string name = "db_deadlift";
            public const int id = 127;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_deadlift_down = MotionAI.Core.Models.Constants.ElmoEnum.db_deadlift_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_deadlift_up = MotionAI.Core.Models.Constants.ElmoEnum.db_deadlift_up;
        }
        public sealed class Db_Fly {
            public const string name = "db_fly";
            public const int id = 121;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_fly_down = MotionAI.Core.Models.Constants.ElmoEnum.db_fly_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_fly__up = MotionAI.Core.Models.Constants.ElmoEnum.db_fly__up;
        }
        public sealed class Db_Front_Raise {
            public const string name = "db_front_raise";
            public const int id = 126;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_front_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.db_front_raise_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_front_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.db_front_raise_up;
        }
        public sealed class Db_Lateral_Raise {
            public const string name = "db_lateral_raise";
            public const int id = 122;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_lateral_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.db_lateral_raise_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_lateral_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.db_lateral_raise_down;
        }
        public sealed class Db_Overhead_Tricep_Extension {
            public const string name = "db_overhead_tricep_extension";
            public const int id = 124;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_overhead_tricep_extension_down = MotionAI.Core.Models.Constants.ElmoEnum.db_overhead_tricep_extension_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_overhead_tricep_extension_up = MotionAI.Core.Models.Constants.ElmoEnum.db_overhead_tricep_extension_up;
        }
        public sealed class Db_Shoulder_Press {
            public const string name = "db_shoulder_press";
            public const int id = 119;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_shoulder_press_up = MotionAI.Core.Models.Constants.ElmoEnum.db_shoulder_press_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_shoulder_press_down = MotionAI.Core.Models.Constants.ElmoEnum.db_shoulder_press_down;
        }
        public sealed class Db_Tricep_Kickback {
            public const string name = "db_tricep_kickback";
            public const int id = 123;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_tricep_kickback_down = MotionAI.Core.Models.Constants.ElmoEnum.db_tricep_kickback_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_tricep_kickback_up = MotionAI.Core.Models.Constants.ElmoEnum.db_tricep_kickback_up;
        }
        public sealed class Db_Upright_Row {
            public const string name = "db_upright_row";
            public const int id = 125;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_upright_row_up = MotionAI.Core.Models.Constants.ElmoEnum.db_upright_row_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum db_upright_row_down = MotionAI.Core.Models.Constants.ElmoEnum.db_upright_row_down;
        }
        public sealed class Dead_Lift {
            public const string name = "dead_lift";
            public const int id = 44;
            public const MotionAI.Core.Models.Constants.ElmoEnum dead_lift_up = MotionAI.Core.Models.Constants.ElmoEnum.dead_lift_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum dead_lift_down = MotionAI.Core.Models.Constants.ElmoEnum.dead_lift_down;
        }
        public sealed class Duck {
            public const string name = "duck";
            public const int id = 90;
            public const MotionAI.Core.Models.Constants.ElmoEnum duck_down = MotionAI.Core.Models.Constants.ElmoEnum.duck_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum duck_up = MotionAI.Core.Models.Constants.ElmoEnum.duck_up;
        }
        public sealed class Fell_A_Tree {
            public const string name = "fell_a_tree";
            public const int id = 84;
            public const MotionAI.Core.Models.Constants.ElmoEnum fell_a_tree_up = MotionAI.Core.Models.Constants.ElmoEnum.fell_a_tree_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum fell_a_tree_down = MotionAI.Core.Models.Constants.ElmoEnum.fell_a_tree_down;
        }
        public sealed class Freestyle {
            public const string name = "freestyle";
            public const int id = 20;
            public const MotionAI.Core.Models.Constants.ElmoEnum freestyle_down = MotionAI.Core.Models.Constants.ElmoEnum.freestyle_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum freestyle_up = MotionAI.Core.Models.Constants.ElmoEnum.freestyle_up;
        }
        public sealed class Frogger {
            public const string name = "frogger";
            public const int id = 46;
            public const MotionAI.Core.Models.Constants.ElmoEnum frogger_down = MotionAI.Core.Models.Constants.ElmoEnum.frogger_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum frogger_up = MotionAI.Core.Models.Constants.ElmoEnum.frogger_up;
        }
        public sealed class Gaming_Movements {
            public const string name = "gaming_movements";
            public const int id = 117;
            public const MotionAI.Core.Models.Constants.ElmoEnum dummy_gaming_elmo_down = MotionAI.Core.Models.Constants.ElmoEnum.dummy_gaming_elmo_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum dummy_gaming_elmo_up = MotionAI.Core.Models.Constants.ElmoEnum.dummy_gaming_elmo_up;
        }
        public sealed class Gesture_Large_B {
            public const string name = "gesture_large_b";
            public const int id = 97;
            public const MotionAI.Core.Models.Constants.ElmoEnum gesture_large_b = MotionAI.Core.Models.Constants.ElmoEnum.gesture_large_b;
        }
        public sealed class Gesture_Large_M {
            public const string name = "gesture_large_m";
            public const int id = 95;
            public const MotionAI.Core.Models.Constants.ElmoEnum gesture_large_m = MotionAI.Core.Models.Constants.ElmoEnum.gesture_large_m;
        }
        public sealed class Gesture_Large_Q {
            public const string name = "gesture_large_q";
            public const int id = 98;
            public const MotionAI.Core.Models.Constants.ElmoEnum gesture_large_q = MotionAI.Core.Models.Constants.ElmoEnum.gesture_large_q;
        }
        public sealed class Good_Morning {
            public const string name = "good_morning";
            public const int id = 40;
            public const MotionAI.Core.Models.Constants.ElmoEnum good_morning_down = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum good_morning_up = MotionAI.Core.Models.Constants.ElmoEnum.good_morning_up;
        }
        public sealed class Hammer {
            public const string name = "hammer";
            public const int id = 81;
            public const MotionAI.Core.Models.Constants.ElmoEnum hammer_down = MotionAI.Core.Models.Constants.ElmoEnum.hammer_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hammer_up = MotionAI.Core.Models.Constants.ElmoEnum.hammer_up;
        }
        public sealed class Hands_In_The_Air_Bounce {
            public const string name = "hands_in_the_air_bounce";
            public const int id = 93;
            public const MotionAI.Core.Models.Constants.ElmoEnum hands_in_the_air_bounce_down = MotionAI.Core.Models.Constants.ElmoEnum.hands_in_the_air_bounce_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hands_in_the_air_bounce_up = MotionAI.Core.Models.Constants.ElmoEnum.hands_in_the_air_bounce_up;
        }
        public sealed class Hands_In_The_Air_Wink {
            public const string name = "hands_in_the_air_wink";
            public const int id = 94;
            public const MotionAI.Core.Models.Constants.ElmoEnum hands_in_the_air_wink_left = MotionAI.Core.Models.Constants.ElmoEnum.hands_in_the_air_wink_left;
            public const MotionAI.Core.Models.Constants.ElmoEnum hands_in_the_air_wink_right = MotionAI.Core.Models.Constants.ElmoEnum.hands_in_the_air_wink_right;
        }
        public sealed class Handwalk {
            public const string name = "handwalk";
            public const int id = 57;
            public const MotionAI.Core.Models.Constants.ElmoEnum handwalk_down = MotionAI.Core.Models.Constants.ElmoEnum.handwalk_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum handwalk_up = MotionAI.Core.Models.Constants.ElmoEnum.handwalk_up;
        }
        public sealed class Heart {
            public const string name = "heart";
            public const int id = 85;
            public const MotionAI.Core.Models.Constants.ElmoEnum heart_down = MotionAI.Core.Models.Constants.ElmoEnum.heart_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum heartUp = MotionAI.Core.Models.Constants.ElmoEnum.heartUp;
        }
        public sealed class High_Knees {
            public const string name = "high_knees";
            public const int id = 26;
            public const MotionAI.Core.Models.Constants.ElmoEnum high_knees_down = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum high_knees_up = MotionAI.Core.Models.Constants.ElmoEnum.high_knees_up;
        }
        public sealed class Hip_Raise {
            public const string name = "hip_raise";
            public const int id = 28;
            public const MotionAI.Core.Models.Constants.ElmoEnum hip_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum hip_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.hip_raise_down;
        }
        public sealed class Hockstrecksprung {
            public const string name = "hockstrecksprung";
            public const int id = 58;
            public const MotionAI.Core.Models.Constants.ElmoEnum hockstrecksprung_down = MotionAI.Core.Models.Constants.ElmoEnum.hockstrecksprung_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hockstrecksprung_up = MotionAI.Core.Models.Constants.ElmoEnum.hockstrecksprung_up;
        }
        public sealed class Hop {
            public const string name = "hop";
            public const int id = 87;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_jump_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_jump_up;
        }
        public sealed class Hop_Group {
            public const string name = "hop_group";
            public const int id = 112;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_group_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_group_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_group_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_group_up;
        }
        public sealed class Hop_Single {
            public const string name = "hop_single";
            public const int id = 115;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_down;
        }
        public sealed class Hop_Single_Left {
            public const string name = "hop_single_left";
            public const int id = 104;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_left_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_left_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_left_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_left_down;
        }
        public sealed class Hop_Single_Right {
            public const string name = "hop_single_right";
            public const int id = 105;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_right_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_right_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_right_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_right_up;
        }
        public sealed class Hop_Single_Straight {
            public const string name = "hop_single_straight";
            public const int id = 116;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_straight_down = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_straight_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum hop_single_straight_up = MotionAI.Core.Models.Constants.ElmoEnum.hop_single_straight_up;
        }
        public sealed class Jumping_Jack {
            public const string name = "jumping_jack";
            public const int id = 5;
            public const MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum jumping_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.jumping_jack_up;
        }
        public sealed class Jump_Tucked {
            public const string name = "jump_tucked";
            public const int id = 38;
            public const MotionAI.Core.Models.Constants.ElmoEnum jump_tucked_down = MotionAI.Core.Models.Constants.ElmoEnum.jump_tucked_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum jump_tucked_up = MotionAI.Core.Models.Constants.ElmoEnum.jump_tucked_up;
        }
        public sealed class La_Fugga {
            public const string name = "la_fugga";
            public const int id = 49;
            public const MotionAI.Core.Models.Constants.ElmoEnum la_fugga_Backward = MotionAI.Core.Models.Constants.ElmoEnum.la_fugga_Backward;
            public const MotionAI.Core.Models.Constants.ElmoEnum la_fugga_Forward = MotionAI.Core.Models.Constants.ElmoEnum.la_fugga_Forward;
        }
        public sealed class Lateral_Raise {
            public const string name = "lateral_raise";
            public const int id = 52;
            public const MotionAI.Core.Models.Constants.ElmoEnum lateral_raise_up = MotionAI.Core.Models.Constants.ElmoEnum.lateral_raise_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum lateral_raise_down = MotionAI.Core.Models.Constants.ElmoEnum.lateral_raise_down;
        }
        public sealed class Lean_Backward {
            public const string name = "lean_backward";
            public const int id = 129;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_backward_down = MotionAI.Core.Models.Constants.ElmoEnum.lean_backward_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_backward_up = MotionAI.Core.Models.Constants.ElmoEnum.lean_backward_up;
        }
        public sealed class Lean_Forward {
            public const string name = "lean_forward";
            public const int id = 128;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_forward_down = MotionAI.Core.Models.Constants.ElmoEnum.lean_forward_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_forward_up = MotionAI.Core.Models.Constants.ElmoEnum.lean_forward_up;
        }
        public sealed class Lean_Side {
            public const string name = "lean_side";
            public const int id = 107;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_up = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_down = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_down;
        }
        public sealed class Lean_Side_Left {
            public const string name = "lean_side_left";
            public const int id = 108;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_left_up = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_left_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_left_down = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_left_down;
        }
        public sealed class Lean_Side_Right {
            public const string name = "lean_side_right";
            public const int id = 109;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_right_down = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_right_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum lean_side_right_up = MotionAI.Core.Models.Constants.ElmoEnum.lean_side_right_up;
        }
        public sealed class Left {
            public const string name = "left";
            public const int id = 113;
            public const MotionAI.Core.Models.Constants.ElmoEnum left_down = MotionAI.Core.Models.Constants.ElmoEnum.left_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum left_up = MotionAI.Core.Models.Constants.ElmoEnum.left_up;
        }
        public sealed class Luftkuss {
            public const string name = "luftkuss";
            public const int id = 91;
            public const MotionAI.Core.Models.Constants.ElmoEnum luft_kuss_forward = MotionAI.Core.Models.Constants.ElmoEnum.luft_kuss_forward;
            public const MotionAI.Core.Models.Constants.ElmoEnum luft_kuss_back = MotionAI.Core.Models.Constants.ElmoEnum.luft_kuss_back;
        }
        public sealed class Lunge {
            public const string name = "lunge";
            public const int id = 12;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_down;
        }
        public sealed class Lunge_Reverse {
            public const string name = "lunge_reverse";
            public const int id = 41;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_reverse_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_reverse_up;
        }
        public sealed class Lunge_Side {
            public const string name = "lunge_side";
            public const int id = 48;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_side_down = MotionAI.Core.Models.Constants.ElmoEnum.lunge_side_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum lunge_side_up = MotionAI.Core.Models.Constants.ElmoEnum.lunge_side_up;
        }
        public sealed class Mountain_Climbers {
            public const string name = "mountain_climbers";
            public const int id = 10;
            public const MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum mountain_climber_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.mountain_climber_jump_down;
        }
        public sealed class New_Movement {
            public const string name = "new_movement";
            public const int id = 69;
            public const MotionAI.Core.Models.Constants.ElmoEnum nd = MotionAI.Core.Models.Constants.ElmoEnum.nd;
            public const MotionAI.Core.Models.Constants.ElmoEnum new_movement = MotionAI.Core.Models.Constants.ElmoEnum.new_movement;
        }
        public sealed class Overhead_Press {
            public const string name = "overhead_press";
            public const int id = 9;
            public const MotionAI.Core.Models.Constants.ElmoEnum overhead_press_up = MotionAI.Core.Models.Constants.ElmoEnum.overhead_press_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum overhead_press_down = MotionAI.Core.Models.Constants.ElmoEnum.overhead_press_down;
        }
        public sealed class Plank {
            public const string name = "plank";
            public const int id = 33;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank = MotionAI.Core.Models.Constants.ElmoEnum.plank;
        }
        public sealed class Plank_Jack {
            public const string name = "plank_jack";
            public const int id = 39;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank_jack_down = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank_jack_up = MotionAI.Core.Models.Constants.ElmoEnum.plank_jack_up;
        }
        public sealed class Plank_Side {
            public const string name = "plank_side";
            public const int id = 51;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank_side = MotionAI.Core.Models.Constants.ElmoEnum.plank_side;
        }
        public sealed class Plank_To_Pushup {
            public const string name = "plank_to_pushup";
            public const int id = 50;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank_to_pushup_Upward = MotionAI.Core.Models.Constants.ElmoEnum.plank_to_pushup_Upward;
            public const MotionAI.Core.Models.Constants.ElmoEnum plank_to_pushup_Downward = MotionAI.Core.Models.Constants.ElmoEnum.plank_to_pushup_Downward;
        }
        public sealed class Pulldown_Lat {
            public const string name = "pulldown_lat";
            public const int id = 77;
            public const MotionAI.Core.Models.Constants.ElmoEnum pulldown_down = MotionAI.Core.Models.Constants.ElmoEnum.pulldown_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum pulldown_up = MotionAI.Core.Models.Constants.ElmoEnum.pulldown_up;
        }
        public sealed class Punch_Slow {
            public const string name = "punch slow";
            public const int id = 89;
            public const MotionAI.Core.Models.Constants.ElmoEnum punch_slow_foward = MotionAI.Core.Models.Constants.ElmoEnum.punch_slow_foward;
            public const MotionAI.Core.Models.Constants.ElmoEnum punch_slow_backward = MotionAI.Core.Models.Constants.ElmoEnum.punch_slow_backward;
        }
        public sealed class Pushup {
            public const string name = "pushup";
            public const int id = 2;
            public const MotionAI.Core.Models.Constants.ElmoEnum pushup_up = MotionAI.Core.Models.Constants.ElmoEnum.pushup_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum pushup_down = MotionAI.Core.Models.Constants.ElmoEnum.pushup_down;
        }
        public sealed class Right {
            public const string name = "right";
            public const int id = 114;
            public const MotionAI.Core.Models.Constants.ElmoEnum right_down = MotionAI.Core.Models.Constants.ElmoEnum.right_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum right_up = MotionAI.Core.Models.Constants.ElmoEnum.right_up;
        }
        public sealed class Rope_Jump {
            public const string name = "rope_jump";
            public const int id = 18;
            public const MotionAI.Core.Models.Constants.ElmoEnum rope_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.rope_jump_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum rope_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.rope_jump_up;
        }
        public sealed class Rope_Jump_Alternating_Feeds {
            public const string name = "rope_jump_alternating_feeds";
            public const int id = 36;
            public const MotionAI.Core.Models.Constants.ElmoEnum rope_jump_alternating_feeds_down = MotionAI.Core.Models.Constants.ElmoEnum.rope_jump_alternating_feeds_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum rope_jump_alternating_feeds_up = MotionAI.Core.Models.Constants.ElmoEnum.rope_jump_alternating_feeds_up;
        }
        public sealed class Row_Hanging {
            public const string name = "row_hanging";
            public const int id = 53;
            public const MotionAI.Core.Models.Constants.ElmoEnum row_hanging_Upward = MotionAI.Core.Models.Constants.ElmoEnum.row_hanging_Upward;
            public const MotionAI.Core.Models.Constants.ElmoEnum row_hanging_Downward = MotionAI.Core.Models.Constants.ElmoEnum.row_hanging_Downward;
        }
        public sealed class Rowing_Ergometer {
            public const string name = "rowing_ergometer";
            public const int id = 45;
            public const MotionAI.Core.Models.Constants.ElmoEnum rowing_ergometer_back = MotionAI.Core.Models.Constants.ElmoEnum.rowing_ergometer_back;
            public const MotionAI.Core.Models.Constants.ElmoEnum rowing_ergometer_forward = MotionAI.Core.Models.Constants.ElmoEnum.rowing_ergometer_forward;
        }
        public sealed class Row_Trx {
            public const string name = "row_trx";
            public const int id = 43;
            public const MotionAI.Core.Models.Constants.ElmoEnum row_trx_down = MotionAI.Core.Models.Constants.ElmoEnum.row_trx_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum row_trx_up = MotionAI.Core.Models.Constants.ElmoEnum.row_trx_up;
        }
        public sealed class Run {
            public const string name = "run";
            public const int id = 30;
            public const MotionAI.Core.Models.Constants.ElmoEnum run_up = MotionAI.Core.Models.Constants.ElmoEnum.run_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum run_down = MotionAI.Core.Models.Constants.ElmoEnum.run_down;
        }
        public sealed class Russian_Twist {
            public const string name = "russian_twist";
            public const int id = 21;
            public const MotionAI.Core.Models.Constants.ElmoEnum russian_twist_left = MotionAI.Core.Models.Constants.ElmoEnum.russian_twist_left;
            public const MotionAI.Core.Models.Constants.ElmoEnum russian_twist_right = MotionAI.Core.Models.Constants.ElmoEnum.russian_twist_right;
        }
        public sealed class Santana_Twist {
            public const string name = "santana twist";
            public const int id = 96;
            public const MotionAI.Core.Models.Constants.ElmoEnum Santana_turn_hand_up = MotionAI.Core.Models.Constants.ElmoEnum.Santana_turn_hand_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum Santana_turn_hand_down = MotionAI.Core.Models.Constants.ElmoEnum.Santana_turn_hand_down;
        }
        public sealed class Sawing {
            public const string name = "sawing";
            public const int id = 82;
            public const MotionAI.Core.Models.Constants.ElmoEnum sawing_forward = MotionAI.Core.Models.Constants.ElmoEnum.sawing_forward;
            public const MotionAI.Core.Models.Constants.ElmoEnum sawing_back = MotionAI.Core.Models.Constants.ElmoEnum.sawing_back;
        }
        public sealed class Screwing {
            public const string name = "screwing";
            public const int id = 83;
            public const MotionAI.Core.Models.Constants.ElmoEnum screwing_right = MotionAI.Core.Models.Constants.ElmoEnum.screwing_right;
            public const MotionAI.Core.Models.Constants.ElmoEnum screwing_left = MotionAI.Core.Models.Constants.ElmoEnum.screwing_left;
        }
        public sealed class Seated_Dip {
            public const string name = "seated_dip";
            public const int id = 80;
            public const MotionAI.Core.Models.Constants.ElmoEnum seated_dip_backward = MotionAI.Core.Models.Constants.ElmoEnum.seated_dip_backward;
            public const MotionAI.Core.Models.Constants.ElmoEnum seated_dip_forward = MotionAI.Core.Models.Constants.ElmoEnum.seated_dip_forward;
        }
        public sealed class Seated_Press {
            public const string name = "seated_press";
            public const int id = 76;
            public const MotionAI.Core.Models.Constants.ElmoEnum vertical_push_forward = MotionAI.Core.Models.Constants.ElmoEnum.vertical_push_forward;
            public const MotionAI.Core.Models.Constants.ElmoEnum vertical_push_backward = MotionAI.Core.Models.Constants.ElmoEnum.vertical_push_backward;
        }
        public sealed class Seated_Row {
            public const string name = "seated_row";
            public const int id = 78;
            public const MotionAI.Core.Models.Constants.ElmoEnum seated_row_back = MotionAI.Core.Models.Constants.ElmoEnum.seated_row_back;
            public const MotionAI.Core.Models.Constants.ElmoEnum seated_row_forward = MotionAI.Core.Models.Constants.ElmoEnum.seated_row_forward;
        }
        public sealed class Shoulder_Press {
            public const string name = "shoulder_press";
            public const int id = 79;
            public const MotionAI.Core.Models.Constants.ElmoEnum shoulder_press_up = MotionAI.Core.Models.Constants.ElmoEnum.shoulder_press_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum shoulder_press_down = MotionAI.Core.Models.Constants.ElmoEnum.shoulder_press_down;
        }
        public sealed class Side_Step {
            public const string name = "side_step";
            public const int id = 106;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_up;
        }
        public sealed class Side_Step_Left {
            public const string name = "side_step_left";
            public const int id = 110;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_left_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_left_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_left_up;
        }
        public sealed class Side_Step_Right {
            public const string name = "side_step_right";
            public const int id = 111;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_right_up = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum side_step_right_down = MotionAI.Core.Models.Constants.ElmoEnum.side_step_right_down;
        }
        public sealed class Situp {
            public const string name = "situp";
            public const int id = 7;
            public const MotionAI.Core.Models.Constants.ElmoEnum situp_down = MotionAI.Core.Models.Constants.ElmoEnum.situp_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum situp_up = MotionAI.Core.Models.Constants.ElmoEnum.situp_up;
        }
        public sealed class Skater {
            public const string name = "skater";
            public const int id = 47;
            public const MotionAI.Core.Models.Constants.ElmoEnum skater_up = MotionAI.Core.Models.Constants.ElmoEnum.skater_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum skater_down = MotionAI.Core.Models.Constants.ElmoEnum.skater_down;
        }
        public sealed class Skipping {
            public const string name = "skipping";
            public const int id = 56;
            public const MotionAI.Core.Models.Constants.ElmoEnum skipping_down = MotionAI.Core.Models.Constants.ElmoEnum.skipping_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum skipping_up = MotionAI.Core.Models.Constants.ElmoEnum.skipping_up;
        }
        public sealed class Spell_Spiral {
            public const string name = "spell_spiral";
            public const int id = 92;
            public const MotionAI.Core.Models.Constants.ElmoEnum spell_spiral = MotionAI.Core.Models.Constants.ElmoEnum.spell_spiral;
        }
        public sealed class Split_Lunge {
            public const string name = "split_lunge";
            public const int id = 27;
            public const MotionAI.Core.Models.Constants.ElmoEnum split_lunge_up = MotionAI.Core.Models.Constants.ElmoEnum.split_lunge_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum split_lunge_down = MotionAI.Core.Models.Constants.ElmoEnum.split_lunge_down;
        }
        public sealed class Sprint {
            public const string name = "sprint";
            public const int id = 31;
            public const MotionAI.Core.Models.Constants.ElmoEnum sprint_down = MotionAI.Core.Models.Constants.ElmoEnum.sprint_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum sprint_up = MotionAI.Core.Models.Constants.ElmoEnum.sprint_up;
        }
        public sealed class Squat_Jump {
            public const string name = "squat_jump";
            public const int id = 19;
            public const MotionAI.Core.Models.Constants.ElmoEnum squat_jump_up = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum squat_jump_down = MotionAI.Core.Models.Constants.ElmoEnum.squat_jump_down;
        }
        public sealed class Squat {
            public const string name = "squat";
            public const int id = 1;
            public const MotionAI.Core.Models.Constants.ElmoEnum squat_down = MotionAI.Core.Models.Constants.ElmoEnum.squat_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum squat_up = MotionAI.Core.Models.Constants.ElmoEnum.squat_up;
        }
        public sealed class Stand_Up {
            public const string name = "stand_up";
            public const int id = 55;
            public const MotionAI.Core.Models.Constants.ElmoEnum stand_up_up = MotionAI.Core.Models.Constants.ElmoEnum.stand_up_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum stand_up_down = MotionAI.Core.Models.Constants.ElmoEnum.stand_up_down;
        }
        public sealed class Superman {
            public const string name = "superman";
            public const int id = 71;
            public const MotionAI.Core.Models.Constants.ElmoEnum superman_up = MotionAI.Core.Models.Constants.ElmoEnum.superman_up;
            public const MotionAI.Core.Models.Constants.ElmoEnum superman_down = MotionAI.Core.Models.Constants.ElmoEnum.superman_down;
        }
        public sealed class Swimmer {
            public const string name = "swimmer";
            public const int id = 70;
            public const MotionAI.Core.Models.Constants.ElmoEnum swimmer_down = MotionAI.Core.Models.Constants.ElmoEnum.swimmer_down;
            public const MotionAI.Core.Models.Constants.ElmoEnum swimmer_up = MotionAI.Core.Models.Constants.ElmoEnum.swimmer_up;
        }
        public sealed class Turn_90 {
            public const string name = "turn_90";
            public const int id = 103;
            public const MotionAI.Core.Models.Constants.ElmoEnum turn_90 = MotionAI.Core.Models.Constants.ElmoEnum.turn_90;
        }
        public sealed class Turn_90_Left {
            public const string name = "turn_90_left";
            public const int id = 102;
            public const MotionAI.Core.Models.Constants.ElmoEnum turn_90_left = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_left;
        }
        public sealed class Turn_90_Right {
            public const string name = "turn_90_right";
            public const int id = 101;
            public const MotionAI.Core.Models.Constants.ElmoEnum turn_90_right = MotionAI.Core.Models.Constants.ElmoEnum.turn_90_right;
        }
    }
}
